{{- if .Values.serviceAccount.create -}}
apiVersion: v2
kind: ServiceAccount
metadata:
  name: {{ include "playlist.serviceAccountName" . }}
  labels:
    {{- include "playlist.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
